ERROR    eawag.datapool  python: Traceback (most recent call last):
ERROR    eawag.datapool  python:   File "<stdin>", line 2, in <module>
ERROR    eawag.datapool  python: ZeroDivisionError: division by zero
ERROR    eawag.datapool  python: 
